import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import Hero from '@/components/Hero'
import FeaturedProducts from '@/components/FeaturedProducts'
import axios from 'axios'
import { GetServerSideProps } from 'next'
import { Products } from '@/types/products'
import LatestProducts from '@/components/LatestProducts'
import ShopOffers from '@/components/ShopOffers'
import UniqueFurniture from '@/components/UniqueProduct'

type Props = {
  data: Products[];
}

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  try {
    // Send HTTP GET request to fetch data from an API
    const response = await axios.get<Products[]>('https://fakestoreapi.com/products');

    // Extract the data from the response
    const data = response.data;

    // Return the data as props
    return { props: { data } };
  } catch (error) {
    console.error(error);
    return { props: { data: [] } };
  }
};

export default function Home({ data }: Props) {
  // console.log("data", data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <FeaturedProducts featuredProducts={data} />
      <LatestProducts latestProducts={data} />
      <ShopOffers
        sectionTitle="What's Hekto Offer?"
        classes="font-JosefinSans text-center text-[#1A0B5B] text-[42px] font-bold mb-20"
      />
      <UniqueFurniture products={data} />
    </>
  )
}
