import Head from 'next/head'
import Hero from '@/components/Hero'
import FeaturedProducts from '@/components/FeaturedProducts/FeaturedProducts'
import axios from 'axios'
import { GetServerSideProps } from 'next'
import { Products } from '@/types/products'
import LatestProducts from '@/components/LatestProducts/LatestProducts'
import ShopOffers from '@/components/ShopOffers'
import UniqueFurniture from '@/components/UniqueProduct'
import TrendingProducts from '@/components/TrendingProducts/TrendingProducts'
import DiscountItems from '@/components/DiscountItems'
import TopCategories from '@/components/TopCategories/TopCategories'
import UpdateBanner from '@/components/UpdateBanner'
import Logos from '@/components/Logos'
import { motion } from "framer-motion";

export type Props = {
  data: Products[];
}

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  try {
    // Send HTTP GET request to fetch data from an API
    const response = await axios.get<Products[]>('https://fakestoreapi.com/products');

    // Extract the data from the response
    const data = response.data;

    // Return the data as props
    return { props: { data } };
  } catch (error) {
    console.error(error);
    return { props: { data: [] } };
  }
};

export default function Home({ data }: Props) {
  // console.log("data", data);
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{
        opacity: "100%",
        transition: { duration: 0.3 },
      }}
      exit={{ opacity: 0, transition: { duration: 0.2 } }}
    >
      <Head>
        <title>E-commercion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <FeaturedProducts featuredProducts={data} />
      <LatestProducts latestProducts={data} />
      <ShopOffers
        sectionTitle="What's Hekto Offer?"
        classes="font-JosefinSans text-center text-[#1A0B5B] text-[42px] font-bold mb-20"
      />
      <UniqueFurniture products={data} />
      <TrendingProducts products={data} />
      <DiscountItems products={data} />
      <TopCategories products={data} />
      <UpdateBanner />
      <Logos />
    </motion.div>
  )
}
